// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file proto/com/qapp/musicQ/musicQ.proto (package com.qapp.musicq, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from service com.qapp.musicq.MusicQ
 */
export const MusicQ = {
  typeName: "com.qapp.musicq.MusicQ",
  methods: {
  }
} as const;

