// @generated by protoc-gen-es v1.4.1 with parameter "target=ts"
// @generated from file proto/com/qapp/zeus/zeus.proto (package com.qapp.zeus, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message com.qapp.zeus.Establishment
 */
export class Establishment extends Message<Establishment> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * @generated from field: optional string profileImage = 4;
   */
  profileImage?: string;

  /**
   * @generated from field: optional string coverImage = 5;
   */
  coverImage?: string;

  /**
   * @generated from field: string street = 6;
   */
  street = "";

  /**
   * @generated from field: string city = 7;
   */
  city = "";

  /**
   * @generated from field: string country = 8;
   */
  country = "";

  constructor(data?: PartialMessage<Establishment>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.Establishment";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "profileImage", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "coverImage", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "street", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "city", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "country", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Establishment {
    return new Establishment().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Establishment {
    return new Establishment().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Establishment {
    return new Establishment().fromJsonString(jsonString, options);
  }

  static equals(a: Establishment | PlainMessage<Establishment> | undefined, b: Establishment | PlainMessage<Establishment> | undefined): boolean {
    return proto3.util.equals(Establishment, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.Event
 */
export class Event extends Message<Event> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * @generated from field: string start_date = 4;
   */
  startDate = "";

  /**
   * @generated from field: string end_date = 5;
   */
  endDate = "";

  /**
   * @generated from field: optional string image = 6;
   */
  image?: string;

  /**
   * @generated from field: float price = 7;
   */
  price = 0;

  /**
   * @generated from field: int32 establishment_id = 8;
   */
  establishmentId = 0;

  /**
   * @generated from field: int32 maximumCapacity = 9;
   */
  maximumCapacity = 0;

  constructor(data?: PartialMessage<Event>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.Event";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "start_date", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "end_date", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "price", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 8, name: "establishment_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "maximumCapacity", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Event {
    return new Event().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJsonString(jsonString, options);
  }

  static equals(a: Event | PlainMessage<Event> | undefined, b: Event | PlainMessage<Event> | undefined): boolean {
    return proto3.util.equals(Event, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.TicketPurchaseResult
 */
export class TicketPurchaseResult extends Message<TicketPurchaseResult> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: int32 user_id = 2;
   */
  userId = 0;

  /**
   * @generated from field: string event_id = 3;
   */
  eventId = "";

  /**
   * @generated from field: float new_balance = 4;
   */
  newBalance = 0;

  constructor(data?: PartialMessage<TicketPurchaseResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.TicketPurchaseResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "user_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "event_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "new_balance", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TicketPurchaseResult {
    return new TicketPurchaseResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TicketPurchaseResult {
    return new TicketPurchaseResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TicketPurchaseResult {
    return new TicketPurchaseResult().fromJsonString(jsonString, options);
  }

  static equals(a: TicketPurchaseResult | PlainMessage<TicketPurchaseResult> | undefined, b: TicketPurchaseResult | PlainMessage<TicketPurchaseResult> | undefined): boolean {
    return proto3.util.equals(TicketPurchaseResult, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.IsManagerOfEstablishmentRequest
 */
export class IsManagerOfEstablishmentRequest extends Message<IsManagerOfEstablishmentRequest> {
  /**
   * @generated from field: int32 userId = 1;
   */
  userId = 0;

  /**
   * @generated from field: int32 establishmentId = 2;
   */
  establishmentId = 0;

  constructor(data?: PartialMessage<IsManagerOfEstablishmentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.IsManagerOfEstablishmentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "userId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "establishmentId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IsManagerOfEstablishmentRequest {
    return new IsManagerOfEstablishmentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IsManagerOfEstablishmentRequest {
    return new IsManagerOfEstablishmentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IsManagerOfEstablishmentRequest {
    return new IsManagerOfEstablishmentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IsManagerOfEstablishmentRequest | PlainMessage<IsManagerOfEstablishmentRequest> | undefined, b: IsManagerOfEstablishmentRequest | PlainMessage<IsManagerOfEstablishmentRequest> | undefined): boolean {
    return proto3.util.equals(IsManagerOfEstablishmentRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.IsManagerOfEstablishmentResponse
 */
export class IsManagerOfEstablishmentResponse extends Message<IsManagerOfEstablishmentResponse> {
  /**
   * @generated from field: bool isManager = 1;
   */
  isManager = false;

  constructor(data?: PartialMessage<IsManagerOfEstablishmentResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.IsManagerOfEstablishmentResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "isManager", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IsManagerOfEstablishmentResponse {
    return new IsManagerOfEstablishmentResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IsManagerOfEstablishmentResponse {
    return new IsManagerOfEstablishmentResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IsManagerOfEstablishmentResponse {
    return new IsManagerOfEstablishmentResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IsManagerOfEstablishmentResponse | PlainMessage<IsManagerOfEstablishmentResponse> | undefined, b: IsManagerOfEstablishmentResponse | PlainMessage<IsManagerOfEstablishmentResponse> | undefined): boolean {
    return proto3.util.equals(IsManagerOfEstablishmentResponse, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.GetEventRequest
 */
export class GetEventRequest extends Message<GetEventRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<GetEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.GetEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventRequest {
    return new GetEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventRequest {
    return new GetEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventRequest {
    return new GetEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventRequest | PlainMessage<GetEventRequest> | undefined, b: GetEventRequest | PlainMessage<GetEventRequest> | undefined): boolean {
    return proto3.util.equals(GetEventRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.GetEstablishmentsRequest
 */
export class GetEstablishmentsRequest extends Message<GetEstablishmentsRequest> {
  constructor(data?: PartialMessage<GetEstablishmentsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.GetEstablishmentsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEstablishmentsRequest {
    return new GetEstablishmentsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEstablishmentsRequest {
    return new GetEstablishmentsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEstablishmentsRequest {
    return new GetEstablishmentsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEstablishmentsRequest | PlainMessage<GetEstablishmentsRequest> | undefined, b: GetEstablishmentsRequest | PlainMessage<GetEstablishmentsRequest> | undefined): boolean {
    return proto3.util.equals(GetEstablishmentsRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.GetEstablishmentsForUserRequest
 */
export class GetEstablishmentsForUserRequest extends Message<GetEstablishmentsForUserRequest> {
  /**
   * @generated from field: int32 userId = 1;
   */
  userId = 0;

  constructor(data?: PartialMessage<GetEstablishmentsForUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.GetEstablishmentsForUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "userId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEstablishmentsForUserRequest {
    return new GetEstablishmentsForUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEstablishmentsForUserRequest {
    return new GetEstablishmentsForUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEstablishmentsForUserRequest {
    return new GetEstablishmentsForUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEstablishmentsForUserRequest | PlainMessage<GetEstablishmentsForUserRequest> | undefined, b: GetEstablishmentsForUserRequest | PlainMessage<GetEstablishmentsForUserRequest> | undefined): boolean {
    return proto3.util.equals(GetEstablishmentsForUserRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.GetEventsRequest
 */
export class GetEventsRequest extends Message<GetEventsRequest> {
  constructor(data?: PartialMessage<GetEventsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.GetEventsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventsRequest {
    return new GetEventsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventsRequest {
    return new GetEventsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventsRequest {
    return new GetEventsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventsRequest | PlainMessage<GetEventsRequest> | undefined, b: GetEventsRequest | PlainMessage<GetEventsRequest> | undefined): boolean {
    return proto3.util.equals(GetEventsRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.GetEventsForEstablishmentRequest
 */
export class GetEventsForEstablishmentRequest extends Message<GetEventsForEstablishmentRequest> {
  /**
   * @generated from field: int32 establishmentId = 1;
   */
  establishmentId = 0;

  constructor(data?: PartialMessage<GetEventsForEstablishmentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.GetEventsForEstablishmentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "establishmentId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventsForEstablishmentRequest {
    return new GetEventsForEstablishmentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventsForEstablishmentRequest {
    return new GetEventsForEstablishmentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventsForEstablishmentRequest {
    return new GetEventsForEstablishmentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventsForEstablishmentRequest | PlainMessage<GetEventsForEstablishmentRequest> | undefined, b: GetEventsForEstablishmentRequest | PlainMessage<GetEventsForEstablishmentRequest> | undefined): boolean {
    return proto3.util.equals(GetEventsForEstablishmentRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.GetEstablishmentRequest
 */
export class GetEstablishmentRequest extends Message<GetEstablishmentRequest> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  constructor(data?: PartialMessage<GetEstablishmentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.GetEstablishmentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEstablishmentRequest {
    return new GetEstablishmentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEstablishmentRequest {
    return new GetEstablishmentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEstablishmentRequest {
    return new GetEstablishmentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetEstablishmentRequest | PlainMessage<GetEstablishmentRequest> | undefined, b: GetEstablishmentRequest | PlainMessage<GetEstablishmentRequest> | undefined): boolean {
    return proto3.util.equals(GetEstablishmentRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.GetEstablishmentsResponse
 */
export class GetEstablishmentsResponse extends Message<GetEstablishmentsResponse> {
  /**
   * @generated from field: repeated com.qapp.zeus.Establishment establishments = 1;
   */
  establishments: Establishment[] = [];

  constructor(data?: PartialMessage<GetEstablishmentsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.GetEstablishmentsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "establishments", kind: "message", T: Establishment, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEstablishmentsResponse {
    return new GetEstablishmentsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEstablishmentsResponse {
    return new GetEstablishmentsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEstablishmentsResponse {
    return new GetEstablishmentsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetEstablishmentsResponse | PlainMessage<GetEstablishmentsResponse> | undefined, b: GetEstablishmentsResponse | PlainMessage<GetEstablishmentsResponse> | undefined): boolean {
    return proto3.util.equals(GetEstablishmentsResponse, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.CreateEstablishmentRequest
 */
export class CreateEstablishmentRequest extends Message<CreateEstablishmentRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: optional string description = 2;
   */
  description?: string;

  /**
   * @generated from field: optional string profileImage = 3;
   */
  profileImage?: string;

  /**
   * @generated from field: optional string coverImage = 4;
   */
  coverImage?: string;

  /**
   * @generated from field: string street = 5;
   */
  street = "";

  /**
   * @generated from field: string city = 6;
   */
  city = "";

  /**
   * @generated from field: string country = 7;
   */
  country = "";

  /**
   * @generated from field: int32 ownerId = 8;
   */
  ownerId = 0;

  constructor(data?: PartialMessage<CreateEstablishmentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.CreateEstablishmentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "profileImage", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "coverImage", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "street", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "city", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "country", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "ownerId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateEstablishmentRequest {
    return new CreateEstablishmentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateEstablishmentRequest {
    return new CreateEstablishmentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateEstablishmentRequest {
    return new CreateEstablishmentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateEstablishmentRequest | PlainMessage<CreateEstablishmentRequest> | undefined, b: CreateEstablishmentRequest | PlainMessage<CreateEstablishmentRequest> | undefined): boolean {
    return proto3.util.equals(CreateEstablishmentRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.SetEstablishmentRoleRequest
 */
export class SetEstablishmentRoleRequest extends Message<SetEstablishmentRoleRequest> {
  /**
   * @generated from field: int32 updaterId = 1;
   */
  updaterId = 0;

  /**
   * @generated from field: int32 establishmentId = 2;
   */
  establishmentId = 0;

  /**
   * @generated from field: int32 userId = 3;
   */
  userId = 0;

  /**
   * @generated from field: string role = 4;
   */
  role = "";

  constructor(data?: PartialMessage<SetEstablishmentRoleRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.SetEstablishmentRoleRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "updaterId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "establishmentId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "userId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetEstablishmentRoleRequest {
    return new SetEstablishmentRoleRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetEstablishmentRoleRequest {
    return new SetEstablishmentRoleRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetEstablishmentRoleRequest {
    return new SetEstablishmentRoleRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SetEstablishmentRoleRequest | PlainMessage<SetEstablishmentRoleRequest> | undefined, b: SetEstablishmentRoleRequest | PlainMessage<SetEstablishmentRoleRequest> | undefined): boolean {
    return proto3.util.equals(SetEstablishmentRoleRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.SetEstablishmentRoleResponse
 */
export class SetEstablishmentRoleResponse extends Message<SetEstablishmentRoleResponse> {
  /**
   * @generated from field: int32 establishmentId = 1;
   */
  establishmentId = 0;

  /**
   * @generated from field: int32 userId = 2;
   */
  userId = 0;

  /**
   * @generated from field: string role = 3;
   */
  role = "";

  constructor(data?: PartialMessage<SetEstablishmentRoleResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.SetEstablishmentRoleResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "establishmentId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "userId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetEstablishmentRoleResponse {
    return new SetEstablishmentRoleResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetEstablishmentRoleResponse {
    return new SetEstablishmentRoleResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetEstablishmentRoleResponse {
    return new SetEstablishmentRoleResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SetEstablishmentRoleResponse | PlainMessage<SetEstablishmentRoleResponse> | undefined, b: SetEstablishmentRoleResponse | PlainMessage<SetEstablishmentRoleResponse> | undefined): boolean {
    return proto3.util.equals(SetEstablishmentRoleResponse, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.GetEventsResponse
 */
export class GetEventsResponse extends Message<GetEventsResponse> {
  /**
   * @generated from field: repeated com.qapp.zeus.Event events = 1;
   */
  events: Event[] = [];

  constructor(data?: PartialMessage<GetEventsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.GetEventsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "events", kind: "message", T: Event, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetEventsResponse {
    return new GetEventsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetEventsResponse {
    return new GetEventsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetEventsResponse {
    return new GetEventsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetEventsResponse | PlainMessage<GetEventsResponse> | undefined, b: GetEventsResponse | PlainMessage<GetEventsResponse> | undefined): boolean {
    return proto3.util.equals(GetEventsResponse, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.CreateEventRequest
 */
export class CreateEventRequest extends Message<CreateEventRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: optional string description = 2;
   */
  description?: string;

  /**
   * @generated from field: string start_date = 3;
   */
  startDate = "";

  /**
   * @generated from field: string end_data = 4;
   */
  endData = "";

  /**
   * @generated from field: optional string image = 5;
   */
  image?: string;

  /**
   * @generated from field: float price = 6;
   */
  price = 0;

  /**
   * @generated from field: int32 establishmentId = 7;
   */
  establishmentId = 0;

  /**
   * @generated from field: int32 maximumCapacity = 8;
   */
  maximumCapacity = 0;

  /**
   * @generated from field: string ticketName = 9;
   */
  ticketName = "";

  constructor(data?: PartialMessage<CreateEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.CreateEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "start_date", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "end_data", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "price", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 7, name: "establishmentId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "maximumCapacity", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "ticketName", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateEventRequest {
    return new CreateEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateEventRequest {
    return new CreateEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateEventRequest {
    return new CreateEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateEventRequest | PlainMessage<CreateEventRequest> | undefined, b: CreateEventRequest | PlainMessage<CreateEventRequest> | undefined): boolean {
    return proto3.util.equals(CreateEventRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.PurchaseTicketRequest
 */
export class PurchaseTicketRequest extends Message<PurchaseTicketRequest> {
  /**
   * @generated from field: string eventId = 1;
   */
  eventId = "";

  /**
   * @generated from field: int32 ticketId = 2;
   */
  ticketId = 0;

  /**
   * @generated from field: int32 userId = 3;
   */
  userId = 0;

  constructor(data?: PartialMessage<PurchaseTicketRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.PurchaseTicketRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "eventId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "ticketId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "userId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PurchaseTicketRequest {
    return new PurchaseTicketRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PurchaseTicketRequest {
    return new PurchaseTicketRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PurchaseTicketRequest {
    return new PurchaseTicketRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PurchaseTicketRequest | PlainMessage<PurchaseTicketRequest> | undefined, b: PurchaseTicketRequest | PlainMessage<PurchaseTicketRequest> | undefined): boolean {
    return proto3.util.equals(PurchaseTicketRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.RefundTicketRequest
 */
export class RefundTicketRequest extends Message<RefundTicketRequest> {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid = "";

  /**
   * @generated from field: int32 userId = 2;
   */
  userId = 0;

  constructor(data?: PartialMessage<RefundTicketRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.RefundTicketRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "userId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefundTicketRequest {
    return new RefundTicketRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefundTicketRequest {
    return new RefundTicketRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefundTicketRequest {
    return new RefundTicketRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RefundTicketRequest | PlainMessage<RefundTicketRequest> | undefined, b: RefundTicketRequest | PlainMessage<RefundTicketRequest> | undefined): boolean {
    return proto3.util.equals(RefundTicketRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.RefundTicketResponse
 */
export class RefundTicketResponse extends Message<RefundTicketResponse> {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid = "";

  /**
   * @generated from field: int32 userId = 2;
   */
  userId = 0;

  /**
   * @generated from field: bool revoked = 3;
   */
  revoked = false;

  constructor(data?: PartialMessage<RefundTicketResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.RefundTicketResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "userId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "revoked", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefundTicketResponse {
    return new RefundTicketResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefundTicketResponse {
    return new RefundTicketResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefundTicketResponse {
    return new RefundTicketResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RefundTicketResponse | PlainMessage<RefundTicketResponse> | undefined, b: RefundTicketResponse | PlainMessage<RefundTicketResponse> | undefined): boolean {
    return proto3.util.equals(RefundTicketResponse, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.UpdateEstablishmentRequest
 */
export class UpdateEstablishmentRequest extends Message<UpdateEstablishmentRequest> {
  /**
   * @generated from field: int32 updater_id = 1;
   */
  updaterId = 0;

  /**
   * @generated from field: int32 id = 2;
   */
  id = 0;

  /**
   * @generated from field: optional string name = 3;
   */
  name?: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: optional string profileImage = 5;
   */
  profileImage?: string;

  /**
   * @generated from field: optional string coverImage = 6;
   */
  coverImage?: string;

  /**
   * @generated from field: optional string street = 7;
   */
  street?: string;

  /**
   * @generated from field: optional string city = 8;
   */
  city?: string;

  /**
   * @generated from field: optional string country = 9;
   */
  country?: string;

  constructor(data?: PartialMessage<UpdateEstablishmentRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.UpdateEstablishmentRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "updater_id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "profileImage", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "coverImage", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "street", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "city", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "country", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateEstablishmentRequest {
    return new UpdateEstablishmentRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateEstablishmentRequest {
    return new UpdateEstablishmentRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateEstablishmentRequest {
    return new UpdateEstablishmentRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateEstablishmentRequest | PlainMessage<UpdateEstablishmentRequest> | undefined, b: UpdateEstablishmentRequest | PlainMessage<UpdateEstablishmentRequest> | undefined): boolean {
    return proto3.util.equals(UpdateEstablishmentRequest, a, b);
  }
}

/**
 * @generated from message com.qapp.zeus.UpdateEventRequest
 */
export class UpdateEventRequest extends Message<UpdateEventRequest> {
  /**
   * @generated from field: int32 updaterId = 1;
   */
  updaterId = 0;

  /**
   * @generated from field: int32 establishmentId = 2;
   */
  establishmentId = 0;

  /**
   * @generated from field: string uuid = 3;
   */
  uuid = "";

  /**
   * @generated from field: optional string name = 4;
   */
  name?: string;

  /**
   * @generated from field: optional string description = 5;
   */
  description?: string;

  /**
   * @generated from field: optional string start_date = 6;
   */
  startDate?: string;

  /**
   * @generated from field: optional string end_date = 7;
   */
  endDate?: string;

  /**
   * @generated from field: optional string image = 8;
   */
  image?: string;

  /**
   * @generated from field: optional float price = 9;
   */
  price?: number;

  /**
   * @generated from field: optional int32 maximumCapacity = 10;
   */
  maximumCapacity?: number;

  constructor(data?: PartialMessage<UpdateEventRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "com.qapp.zeus.UpdateEventRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "updaterId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "establishmentId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "start_date", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "end_date", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "price", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
    { no: 10, name: "maximumCapacity", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateEventRequest {
    return new UpdateEventRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateEventRequest {
    return new UpdateEventRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateEventRequest {
    return new UpdateEventRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateEventRequest | PlainMessage<UpdateEventRequest> | undefined, b: UpdateEventRequest | PlainMessage<UpdateEventRequest> | undefined): boolean {
    return proto3.util.equals(UpdateEventRequest, a, b);
  }
}

