// @generated by protoc-gen-connect-es v1.1.4 with parameter "target=ts,import_extension=none"
// @generated from file proto/com/qapp/cerberus/cerberus.proto (package com.qapp.cerberus, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUserDataRequest, GetUserDataResponse, GoogleLoginRequest, LoginRequest, LoginResponse, RegisterRequest, RegisterResponse, UpdateUserDataRequest, UpdateUserDataResponse } from "./cerberus_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service com.qapp.cerberus.AuthService
 */
export const AuthService = {
  typeName: "com.qapp.cerberus.AuthService",
  methods: {
    /**
     * @generated from rpc com.qapp.cerberus.AuthService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: RegisterResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.qapp.cerberus.AuthService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.qapp.cerberus.AuthService.GoogleOAuthLogin
     */
    googleOAuthLogin: {
      name: "GoogleOAuthLogin",
      I: GoogleLoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.qapp.cerberus.AuthService.GetUserData
     */
    getUserData: {
      name: "GetUserData",
      I: GetUserDataRequest,
      O: GetUserDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc com.qapp.cerberus.AuthService.UpdateUserData
     */
    updateUserData: {
      name: "UpdateUserData",
      I: UpdateUserDataRequest,
      O: UpdateUserDataResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

